spring:
  datasource:
    url: jdbc:postgresql://192.168.15.89:5432/security
    username: postgres
    password: 1234


  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false

server:
  port: 8081